name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: extension

      - name: Run linter
        run: npm run lint
        working-directory: extension

      - name: Type check
        run: npm run check-types
        working-directory: extension

      - name: Run tests
        run: npm test
        working-directory: extension

      - name: Build project
        run: npm run package
        working-directory: extension
