name: Test Coverage Report

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: extension/package-lock.json

      - name: Install extension dependencies
        run: |
          cd extension
          npm ci

      - name: Run tests with coverage
        run: |
          cd extension
          npm run test:coverage

      - name: Copy coverage report to documentation
        run: |
          cd extension
          node copy-coverage.js

      - name: Generate coverage report
        run: |
          echo "Coverage report generated successfully"
          echo "Files in coverage directory:"
          ls -la documentation/static/test-coverage/ || echo "No coverage files found"

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: documentation/static/test-coverage/
          retention-days: 30
